version: "3.8"

services:
  # frontend:
  #   image: node:18
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_API_URL=http://backend:5000

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
      - "50051:50051"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/raffle_app
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app
      - ./protos:/app/protos
    working_dir: /app

  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/raffle_app
      - REDIS_URL=redis://redis:6379
      - GRPC_SERVER_HOST=backend
      - GRPC_SERVER_PORT=50051
    depends_on:
      - backend
      - mongodb
      - redis
    volumes:
      - ./fastapi:/app
      - ./protos:/app/protos
    working_dir: /app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongodb_data: