version: "3.8"

services:
  # frontend:
  #   image: node:18
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_API_URL=http://backend:5000

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/raffle_app
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6378:6378"

volumes:
  mongodb_data:
