# docker-compose.yml
version: '3.8'

services:
  app:
    container_name: lucky_fastapi
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
      - "8766:8766"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - REDIS_URL=redis://redis
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8766
    restart: always

  mongodb:
    container_name: lucky_db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    container_name: lucky_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: