# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import raffle_pb2 as raffle__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in raffle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RaffleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PurchaseTickets = channel.unary_unary(
                '/raffle.RaffleService/PurchaseTickets',
                request_serializer=raffle__pb2.PurchaseTicketsRequest.SerializeToString,
                response_deserializer=raffle__pb2.PurchaseTicketsResponse.FromString,
                _registered_method=True)
        self.GetCurrentRaffle = channel.unary_unary(
                '/raffle.RaffleService/GetCurrentRaffle',
                request_serializer=raffle__pb2.GetCurrentRaffleRequest.SerializeToString,
                response_deserializer=raffle__pb2.GetCurrentRaffleResponse.FromString,
                _registered_method=True)
        self.IncreaseBalance = channel.unary_unary(
                '/raffle.RaffleService/IncreaseBalance',
                request_serializer=raffle__pb2.IncreaseBalanceRequest.SerializeToString,
                response_deserializer=raffle__pb2.IncreaseBalanceResponse.FromString,
                _registered_method=True)
        self.GetRaffleResults = channel.unary_unary(
                '/raffle.RaffleService/GetRaffleResults',
                request_serializer=raffle__pb2.GetRaffleResultsRequest.SerializeToString,
                response_deserializer=raffle__pb2.GetRaffleResultsResponse.FromString,
                _registered_method=True)


class RaffleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PurchaseTickets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentRaffle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncreaseBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRaffleResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaffleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PurchaseTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseTickets,
                    request_deserializer=raffle__pb2.PurchaseTicketsRequest.FromString,
                    response_serializer=raffle__pb2.PurchaseTicketsResponse.SerializeToString,
            ),
            'GetCurrentRaffle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentRaffle,
                    request_deserializer=raffle__pb2.GetCurrentRaffleRequest.FromString,
                    response_serializer=raffle__pb2.GetCurrentRaffleResponse.SerializeToString,
            ),
            'IncreaseBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.IncreaseBalance,
                    request_deserializer=raffle__pb2.IncreaseBalanceRequest.FromString,
                    response_serializer=raffle__pb2.IncreaseBalanceResponse.SerializeToString,
            ),
            'GetRaffleResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRaffleResults,
                    request_deserializer=raffle__pb2.GetRaffleResultsRequest.FromString,
                    response_serializer=raffle__pb2.GetRaffleResultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raffle.RaffleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('raffle.RaffleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RaffleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PurchaseTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raffle.RaffleService/PurchaseTickets',
            raffle__pb2.PurchaseTicketsRequest.SerializeToString,
            raffle__pb2.PurchaseTicketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentRaffle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raffle.RaffleService/GetCurrentRaffle',
            raffle__pb2.GetCurrentRaffleRequest.SerializeToString,
            raffle__pb2.GetCurrentRaffleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncreaseBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raffle.RaffleService/IncreaseBalance',
            raffle__pb2.IncreaseBalanceRequest.SerializeToString,
            raffle__pb2.IncreaseBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRaffleResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raffle.RaffleService/GetRaffleResults',
            raffle__pb2.GetRaffleResultsRequest.SerializeToString,
            raffle__pb2.GetRaffleResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
