# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"\"\n\rRaffleRequest\x12\x11\n\traffle_id\x18\x01 \x01(\t\"1\n\x0eRaffleResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2U\n\rRaffleService\x12\x44\n\x0fGetRaffleStatus\x12\x16.service.RaffleRequest\x1a\x17.service.RaffleResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAFFLEREQUEST']._serialized_start=26
  _globals['_RAFFLEREQUEST']._serialized_end=60
  _globals['_RAFFLERESPONSE']._serialized_start=62
  _globals['_RAFFLERESPONSE']._serialized_end=111
  _globals['_RAFFLESERVICE']._serialized_start=113
  _globals['_RAFFLESERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
