# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthenticateTelegram = channel.unary_unary(
                '/auth.AuthService/AuthenticateTelegram',
                request_serializer=auth__pb2.AuthTelegramRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthTelegramResponse.FromString,
                _registered_method=True)
        self.UpdateTonWallet = channel.unary_unary(
                '/auth.AuthService/UpdateTonWallet',
                request_serializer=auth__pb2.UpdateTonWalletRequest.SerializeToString,
                response_deserializer=auth__pb2.UpdateTonWalletResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/auth.AuthService/ValidateToken',
                request_serializer=auth__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.UpdateUserReferral = channel.unary_unary(
                '/auth.AuthService/UpdateUserReferral',
                request_serializer=auth__pb2.UpdateUserReferralRequest.SerializeToString,
                response_deserializer=auth__pb2.UpdateUserReferralResponse.FromString,
                _registered_method=True)
        self.ListUserReferrals = channel.unary_unary(
                '/auth.AuthService/ListUserReferrals',
                request_serializer=auth__pb2.ListUserReferralsRequest.SerializeToString,
                response_deserializer=auth__pb2.ListUserReferralsResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/auth.AuthService/GetConfig',
                request_serializer=auth__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=auth__pb2.GetConfigResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AuthenticateTelegram(self, request, context):
        """Authenticate or create user with Telegram ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTonWallet(self, request, context):
        """Update TON wallet
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Validate token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserReferral(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserReferrals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthenticateTelegram': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateTelegram,
                    request_deserializer=auth__pb2.AuthTelegramRequest.FromString,
                    response_serializer=auth__pb2.AuthTelegramResponse.SerializeToString,
            ),
            'UpdateTonWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTonWallet,
                    request_deserializer=auth__pb2.UpdateTonWalletRequest.FromString,
                    response_serializer=auth__pb2.UpdateTonWalletResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=auth__pb2.ValidateTokenRequest.FromString,
                    response_serializer=auth__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'UpdateUserReferral': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserReferral,
                    request_deserializer=auth__pb2.UpdateUserReferralRequest.FromString,
                    response_serializer=auth__pb2.UpdateUserReferralResponse.SerializeToString,
            ),
            'ListUserReferrals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserReferrals,
                    request_deserializer=auth__pb2.ListUserReferralsRequest.FromString,
                    response_serializer=auth__pb2.ListUserReferralsResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=auth__pb2.GetConfigRequest.FromString,
                    response_serializer=auth__pb2.GetConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthenticateTelegram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AuthenticateTelegram',
            auth__pb2.AuthTelegramRequest.SerializeToString,
            auth__pb2.AuthTelegramResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTonWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateTonWallet',
            auth__pb2.UpdateTonWalletRequest.SerializeToString,
            auth__pb2.UpdateTonWalletResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ValidateToken',
            auth__pb2.ValidateTokenRequest.SerializeToString,
            auth__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserReferral(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateUserReferral',
            auth__pb2.UpdateUserReferralRequest.SerializeToString,
            auth__pb2.UpdateUserReferralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserReferrals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListUserReferrals',
            auth__pb2.ListUserReferralsRequest.SerializeToString,
            auth__pb2.ListUserReferralsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetConfig',
            auth__pb2.GetConfigRequest.SerializeToString,
            auth__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
